- name: Installing packages
  yum: name={{ item }}
  with_items:
      - vim
      - wget
      - iftop
      - iotop
      - sysstat
      - hdparm
      - atop
      - lshw
      - tmux
      - python-pip

